export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY = "ADJUST_QTY";

export const INCREAMENT_ITEMS = "INCREAMENT_ITEMS";
export const DECREAMENT_ITEMS = "DECREAMENT_ITEMS";
